version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: DB_healio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: healio_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpAdmin_healio
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "1010:80"
    depends_on:
      - mysql
volumes:
  mysql_data:
